name: Continuous Delivery

on:
  push:
    branches:
      - "**"

permissions:
  contents: write
  
jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: dotnet build -c Release
      - name: Test
        run: dotnet test -c Release --no-build

  release:
    name: Release
    uses: ./.github/workflows/release.yml
    needs: build-and-test
    with:
      project_path: src/Project
      project_name: Project
    secrets: 
      nuget_api_key: ${{ secrets.NUGET_API_KEY }}

  echo-release:
    name: Output Release Information
    runs-on: ubuntu-latest
    needs: release
    timeout-minutes: 5
    steps:
      - run: |
          echo "Release tag: ${{ needs.release.outputs.release_tag }}"
          echo "Release URL: ${{ needs.release.outputs.release_url }}"
          echo "Version: ${{ needs.release.outputs.major_version }}.${{ needs.release.outputs.minor_version }}.${{ needs.release.outputs.patch_version }}"
          echo "NuGet package URL: ${{ needs.release.outputs.nuget_package_url }}"
